name       : distrom
version    : 3.3.4
release    : 3
source     : 
    - https://github.com/gdabah/distorm/archive/v3.3.4.tar.gz : 28e766b116a9b8294ff5ceb1dcfd83a9b0e2ffba1dfbbb6ef84ab18f9b138aee
license    : BSD
component  : reverse engineering
summary    : binary stream disassembler library project
description: |
    diStorm3 is really a decomposer, which means it takes an instruction and returns a binary structure which describes it 
    rather than static text, which is great for advanced binary code analysis.
install    : |
    %python_install
