name       : thc-hydra
version    : 8.6
release    : 5
source     : 
    - https://github.com/vanhauser-thc/thc-hydra/archive/8.6.tar.gz : 05a87eb018507b24afca970081f067e64441460319fb75ca1e64c4a1f322b80b
license    : GPL-3.0
component  : password attacks
summary    : Very fast network logon cracker
description: |
    A very fast network logon cracker which support many different services.
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
