name       : wapiti 
version    : 2.3.0
release    : 16
license    : GPL-2.0
component  : web applications
summary    : web scanner
description: |
    Wapiti is a vulnerability scanner for web applications. It currently search vulnerabilities like XSS, 
    SQL and XPath injections, file inclusions, command execution, XXE injections, CRLF injections... 
    It use the Python programming language.
source     :
    - https://ncu.dl.sourceforge.net/project/wapiti/wapiti/wapiti-2.3.0/wapiti-2.3.0.tar.gz : 6b836a4810f17b7eda4345fb12293112129961ba243140c72a8da0ac2572f4b4
install    : |
    %python3_install
