name       : yara
version    : 3.7.0
release    : 15
source     : 
    - https://github.com/VirusTotal/yara/archive/v3.7.0.tar.gz : 01f0841e7387918c2b6d0b7fb48014bda41d1487be1cabf718a0576018969641 
license    : GPL-3.0
component  : reverse engineering
summary    : The pattern matching swiss knife 
description: |
    YARA is a tool aimed at (but not limited to) helping malware researchers to identify and classify malware samples.
setup      : |
    ./bootstrap.sh
build      : |
    %configure
    %make
install    : |
    %make_install
