name       : hashdeep
version    : 4.4
release    : 3 
license    : GPL-2.0
component  : forensics
summary    : Advanced checksum hashing tool
description: |
    This is md5deep, a set of cross-platform tools to compute hashes, or message digests, 
    for any number of files while optionally recursively digging through the directory structure.
source     :
    - https://github.com/jessek/hashdeep/archive/v4.4.tar.gz : ad78d42142f9a74fe8ec0c61bc78d6588a528cbb9aede9440f50b6ff477f3a7f
setup      : |
    sh bootstrap.sh
    %configure
build      : |
    %make
install    : |
    %make_install
