name       : binwalk
version    : 2.1.2
release    : 4
source     : 
    - https://github.com/ReFirmLabs/binwalk/archive/v2.1.1.tar.gz : 1b70a5b03489d29f60fef18008a2164974234874faab48a4f47ec53d461d284a
license    : MIT
component  : forensics
summary    : tool for analyzing, reverse engineering, and extracting firmware images.
description: |
    Binwalk is a tool for searching a given binary image for embedded files and executable code. 
    Specifically, it is designed for identifying files and code embedded inside of firmware images.
install    : |
    %python_install
