name       : bandicoot
version    : 0.5
release    : 5
license    : MIT
component  : mobile
summary    : an open-source python toolbox to analyze mobile phone metadata
description: |
    bandicoot is Python toolbox to analyze mobile phone metadata. It provides a complete, 
    easy-to-use environment for data-scientist to analyze mobile phone metadata. 
source     :
    - https://github.com/yvesalexandre/bandicoot/archive/0.5.tar.gz : 49deed2ef385cb1983ac4c21e0776397312838b94c61289816d34d0e04cf905b
install    : |
    %python3_install
